name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: pdo, pdo_mysql, mbstring, curl, zip, json
    
    - name: Install Composer dependencies
      working-directory: "./Desktop/Code Projects/Patone"
      run: composer install --prefer-dist --no-progress
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Node dependencies
      working-directory: "./Desktop/Code Projects/Patone"
      run: npm install
    
    - name: Run PHP tests
      working-directory: "./Desktop/Code Projects/Patone"
      run: vendor/bin/phpunit --configuration phpunit.xml
    
    - name: Run JavaScript tests
      working-directory: "./Desktop/Code Projects/Patone"
      run: npm test

  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install MkDocs
      run: pip install mkdocs
    
    - name: Build documentation
      run: mkdocs build -f documentation/mkdocs.yml -d documentation/site
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/site